port: 7880
rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 50100
  use_external_ip: false
  node_ip: 192.168.1.100 # set to your host/LAN IP
redis:
  address: redis:6379
keys:
  1uhwH2Iv3aGFNTCGC3bNv0OhBjsffTdgJJiGDgYfJKw=: vh+pYw6eg1DQaMPZH4tdS3t39fwTRvuA4XEqNF37Mf8=
logging:
  level: info
  json: false
  sample: false
room:
  auto_create: true
  empty_timeout: 300
  max_participants: 50
webhook:
  urls:
    # optional
  api_key: 1uhwH2Iv3aGFNTCGC3bNv0OhBjsffTdgJJiGDgYfJKw=
